(defun SCORE->GRADE (s) (if (numberp s) (if (>= s 90) (car (cons 'a nil)) 
						(if (>= s 87) (car (cons 'a- nil))
						(if (>= s 83) (car (cons 'b+ nil))
						(if (>= s 80) (car (cons 'b nil))
						(if (>= s 77) (car (cons 'b- nil))
						(if (>= s 73) (car (cons 'c+ nil))
						(if (>= s 70) (car (cons 'c nil))
						(if (>= s 60) (car (cons 'd nil))
						(car (cons 'f nil))
							)))))))) nil))